x=5
print('hello \n' + str(x))
print (x)
name = input('whats your name?\n')
name = name + ' Abuhazera'
print('your name is '+ name)
UPname = name.upper()
DNname = name.lower()
CAPname = name.capitalize()
COUNTname = name.count('a')
print (UPname + ' '+ DNname + ' ' + CAPname + ' ' + str(COUNTname ))
output =  'Hello, {0} {1} and {1}'.format (UPname,CAPname)
print('1111111111111111111111')
print(output)
print (f'Hel what ,{DNname} + {UPname}')
